### PR TITLE
Protect backoff strategies from overflowing `time.Duration`.

### LINKED ISSUE #16: Issue with random number generation for jitter.
```
panic: invalid argument to Int63n

goroutine 26 [running]:
math/rand.(*Rand).Int63n(0xc00009c420, 0x8000000000000001, 0x3ff0000000000000)
	/usr/local/Cellar/go/1.13.6/libexec/src/math/rand/rand.go:111 +0x11d
math/rand.Int63n(...)
	/usr/local/Cellar/go/1.13.6/libexec/src/math/rand/rand.go:319
github.com/dogmatiq/linger.Rand(0x0, 0x8000000000000000, 0x3f847ae147ae147b)
	/Users/james/go/pkg/mod/github.com/dogmatiq/linger@v0.2.0/jitter.go:42 +0x55
github.com/dogmatiq/linger.FullJitter(0x8000000000000000, 0x0)
	/Users/james/go/pkg/mod/github.com/dogmatiq/linger@v0.2.0/jitter.go:14 +0x34
github.com/dogmatiq/linger/backoff.WithTransforms.func1(0x0, 0x0, 0x28, 0x4505013)
	/Users/james/go/pkg/mod/github.com/dogmatiq/linger@v0.2.0/backoff/strategy.go:71 +0x84
github.com/dogmatiq/linger/backoff.(*Counter).Fail(0xc0001f6798, 0x0, 0x0, 0x0)
	/Users/james/go/pkg/mod/github.com/dogmatiq/linger@v0.2.0/backoff/counter.go:40 +0x54
github.com/dogmatiq/linger/backoff.(*Counter).Sleep(0xc0001f6798, 0x485ec80, 0xc0001f67c0, 0x0, 0x0, 0x24, 0x0)
	/Users/james/go/pkg/mod/github.com/dogmatiq/linger@v0.2.0/backoff/counter.go:53 +0x43
github.com/dogmatiq/infix/persistence/provider/sql.(*cursor).Next(0xc0001f6780, 0x485ec80, 0xc0001f67c0, 0x0, 0x0, 0x0)
	/Users/james/grit/github.com/dogmatiq/infix/persistence/provider/sql/stream.go:214 +0x238
github.com/dogmatiq/infix/app/projection.(*Projector).consumeNext(0xc0001d0000, 0x485ec80, 0xc000134140, 0x4857480, 0xc0001f6780, 0x0, 0x0)
	/Users/james/grit/github.com/dogmatiq/infix/app/projection/projector.go:181 +0x71
github.com/dogmatiq/infix/app/projection.(*Projector).consume(0xc0001d0000, 0x485ec80, 0xc000134140, 0x0, 0x0)
	/Users/james/grit/github.com/dogmatiq/infix/app/projection/projector.go:138 +0x553
github.com/dogmatiq/infix/app/projection.(*Projector).Run(0xc0001d0000, 0x485ec80, 0xc000134140, 0xc000168088, 0xc00007a838)
	/Users/james/grit/github.com/dogmatiq/infix/app/projection/projector.go:70 +0x137
github.com/dogmatiq/infix.(*Engine).streamEvents.func1(0xc00004e768, 0xc00004e798)
	/Users/james/grit/github.com/dogmatiq/infix/app.go:57 +0x3f
golang.org/x/sync/errgroup.(*Group).Go.func1(0xc000142270, 0xc0001324e0)
	/Users/james/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:57 +0x64
created by golang.org/x/sync/errgroup.(*Group).Go
	/Users/james/go/pkg/mod/golang.org/x/sync@v0.0.0-20190911185100-cd5d95a43a6e/errgroup/errgroup.go:54 +0x66
```

### PR DESCRIPTION
**Pull request by jmalloc**
Fixes #16

### CODE REVIEW

**Review by danilvpetrov — APPROVED** [review]
That makes sense. That, in fact, reminded me of `ax`'s retry logic when duration was overflowing after exponential back off periods.

**Comment by jmalloc** [comment]
Oh did we already handle overflows there?  I wasn't sure if I had this right, but I found this, which verifies this approach is valid:

https://www.geeksforgeeks.org/check-integer-overflow-multiplication/

(For the `Linear()` strategy, that is).

**Comment by danilvpetrov** [comment]
Yeah, we definitely handled overflows in `ax`'s retry policy. One of the best tests (not unit tests, unfortunately) for this stuff I found is to place this kind of policies and strategies in the infinite loop and don't observe sleeping intervals to simulate time lapsing. After about 30 iterations exponential backoff is guaranteed to panic if it does not handle overflows correctly.

**Comment by jmalloc** [comment]
I sort of did that accidentally in infix :) after a while of receiving no messages the SQL-based stream (which polls the table after a backoff delay) was causing it to overflow quite quickly.

**Pull request merged**
